
[[dependencies]]
  branch = "master"
  name = "github.com/caarlos0/spin"

[[dependencies]]
  branch = "master"
  name = "github.com/google/go-github"

[[dependencies]]
  branch = "master"
  name = "github.com/urfave/cli"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/oauth2"
